### ISSUE TITLE
Overcoming scalability issues in your Prometheus ecosystem

### ISSUE THREAD

**Issue by jetzlstorfer** [cloudnativemcr/speakers#1]
* **Title**: Overcoming scalability issues in your Prometheus ecosystem
* **Speaker**: Jürgen Etzlstorfer
* **Type**: Presentation 30-45 mins
* **Level**: standard
* **Tags**: kubernetes, devops, prometheus, grafana, continuous delivery

**Description**

Prometheus is considered a foundational building block when running applications on Kubernetes and has become the de-facto open-source standard for visibility and monitoring in Kubernetes environments.
Your first starting points when operating Prometheus are most probably configuring scraping to pull your metrics from your services, building dashboards on top of your data with Grafana, or defining alerts for important metrics breaching thresholds in your production environment. in your production environment.

As soon as you are comfortable with Prometheus as your weapon of choice, your next challenges will be scaling and managing Prometheus for your whole fleet of applications and environments. As the journey “From Zero to Prometheus Hero” is not trivial you will find obstacles on the way. In this blog we are highlighting the most common challenges we have seen and provide guidance on how to overcome them. Finally, we are discussing a solution to get you there more quickly to build automated, future-proof observability with Prometheus showing Keptn as one possible implementation.

**Speaker Bio** (optional)

Jürgen is a core contributor to the Keptn open-source project and responsible for the strategy and integration of self-healing techniques and tools into the Keptn framework. He also loves to share his experience, most recently at conferences on Kubernetes based technologies and automation.

**Comment by yankcrime** [comment]
Thanks @jetzlstorfer, this looks great!  We're planning the June meetup now, we'll be back in touch once we've worked out a few options for dates so we can get this scheduled and announced.

**Comment by jetzlstorfer** [comment]
Thanks @yankcrime, looking forward to the meetup!

**Comment by yankcrime** [comment]
We've just announced this meetup for June 10th - see you there @jetzlstorfer! 🎉

https://www.meetup.com/Cloud-Native-Kubernetes-Manchester/events/270954056/

**Comment by jetzlstorfer** [comment]
Great - looking forward!
