### ISSUE TITLE
Independent Testing Environments for Kubernetes: How and Why

### ISSUE THREAD

**Issue by BenElgar** [cloudnativemcr/speakers#2]
* **Title**: Independent Testing Environments for Kubernetes: How and Why
* **Speaker**: Ben Elgar
* **Type**: Presentation 30-45 mins
* **Level**:  standard
* **Tags**: kubernetes, devops

**Description**

In this talk we'll discuss what it means to have independent testing environments in Kubernetes and why they provide value. We'll then discuss the various means of creating those environments at scale and integrating them into your continuous integration and delivery pipelines. Finally we'll include a demo of [Krucible](https://usekrucible.com), a platform for creating testing and development environments in Kubernetes and then take any questions.

**Speaker Bio** (optional)

Ben is a software engineer and founder of Krucible, a platform for creating Kubernetes clusters for development and testing. He previously worked at MongoDB on their enterprise Kubernetes team where he helped develop their in-house testing solutions.

**Comment by mattj-io** [comment]
Hey @BenElgar - thanks for this, sounds awesome ! We're currently booking for July's virtual event so once we nail down a date we will give you a shout.

**Comment by BenElgar** [comment]
Cheers @mattj-io! Sounds grand!

**Comment by thomasriley** [comment]
Hey @BenElgar - we are just thinking about provisional dates. Would a virtual event on 8th July @ 6PM work for you?

**Comment by BenElgar** [comment]
Hi @thomasriley! Yes, that works for me. :)

**Comment by thomasriley** [comment]
Hello @BenElgar - my apologies for not getting back to you sooner. The 8th July conflicts with other local meetups that are virtual so we have not locked that date in. We will reply again soon once we have determine another day to check your availability.

Stay safe! 👍

**Comment by BenElgar** [comment]
@thomasriley No worries! Sounds good. :slightly_smiling_face:

**Comment by yankcrime** [comment]
Hi @BenElgar - could you make August 6th?

**Comment by yankcrime** [comment]
@BenElgar The meetup's now live, see you there! https://www.meetup.com/Cloud-Native-Kubernetes-Manchester/events/272042108/

**Comment by BenElgar** [comment]
Excellent, thank you!
