### ISSUE TITLE
Putting a VIP in your clusters for both HA and Load-Balancing

### ISSUE THREAD

**Issue by thebsdbox** [cloudnativemcr/speakers#3]
* **Title**: 

Putting a VIP in your clusters for both HA and Load-Balancing

* **Speaker**: 

Dan Finneran

* **Type**: (Presentation 30-45 mins | Lightning Talk 5-10 mins)

Presentation

* **Level**: (basic | standard | advanced)

Standard, there will be a bit of a deep dive into networking and kubernetes services architecture.

* **Tags**: (e.g. kubernetes, devops, live-coding, workshop)

kubernetes, HA, Load-Balancing, services, networking

**Description**

*Please Provide a small paragraph that describes your proposal*

After working with various customers and end-users over the last few years I developed an itch that required scratching, namely that deploying, automating, scaling, upgrading and repairing of HA Kubernetes clusters was a pain. Traditionally the approach required using numerous layered tooling to provide this functionality (along with their own configurations to manage), I decided that there may be a better approach. The original design has continued to grow and grow in terms of functionality (scope creep 😱 ), but it's been a fun experience so far. 

This session will cover:
- The requirements for a HA Kubernetes cluster and the problems it presents
- The design for an alternative approach with [kube-vip.io](https://kube-vip.io)
- Expanding the architecture to manage service `type:LoadBalancer`

**Speaker Bio** (optional)

*A short bio of the speaker*

`TBD`

**Comment by mattj-io** [comment]
Hey Dan, thanks for that - talk sounds awesome ! Will get you scheduled in for one of our upcoming events.
