### ISSUE TITLE
Experimenting with Deno for Easier Kubernetes Deployments / Yshay Yaacobi

### ISSUE THREAD

**Issue by shar1z** [cloudnativemcr/speakers#4]
* **Title**:  Experimenting with Deno for Easier Kubernetes Deployments
* **Speaker**: Yshay Yaacobi
* **Type**: Presentation 30-45 mins (can also be a lightning talk)
* **Level**: Standard / Advanced
* **Tags**: Kubernetes, live-coding, Deno

**Description**
One of Kubernetes' greatest innovations lies in its resource model.  Kubernetes made it possible to define every application, infrastructure component, or configuration declaratively in complex microservices architectures.  This enabled engineers to easily declare complex configuration as resources in a single YAML file. However, as we all know, managing huge YAML configurations can become very difficult and messy when the operations grow and scale. This talk will showcase a small OSS toolkit that use Typescript & Deno to compose complex declarations of Kubernetes apps and resources. We discuss to pros/cons of such approach and how it stacks against other tools & practices.

*Please Provide a small paragraph that describes your proposal*
As we all know, dealing with Kubernetes YAML is not very intuitive (especially for those just getting starting) and the more resources and dependencies are added the messier and more complex the process becomes. In this talk, we'll explore how we can use Typescript and Deno to bring typing, composition, code-reuse, and testing as an alternative to YAML - that doesn't include these capabilities, all while still remaining declarative and easy to use.

**Speaker Bio** (optional)
Yshay Yaacobi is the co-founder and CTO at Livecyle, an early-stage startup that specializes in collaboration on top of live environments.  Yshay has more than a decade of experience with web and cloud technologies, has given local talks about various technologies and is co-organizer of the Rx-Israel meetup group.

He is passionate about programming languages, functional programming, cloud and system architecture.  Yshay is extremely interested in open source, and is the lead developer of Tweek (git.io/tweek) - a cloud native open-source feature manager. Over the last few years Yshay has been using Docker and Kubernetes heavily and has also given sessions in several cloud-native/devops meetups and events

*A short bio of the speaker*

**Comment by mattj-io** [comment]
Thanks @shar1z ! We'll take a look at both of these and get back to you soon

**Comment by shar1z** [comment]
Thank you @mattj-io!! Hope we'll be able to collaborate on the community circuit again! :-)
