### ISSUE TITLE
What we learned from reading 100+ Kubernetes Post-Mortems / Shimon Tolts + Noaa Barki

### ISSUE THREAD

**Issue by shar1z** [cloudnativemcr/speakers#5]
* **Title**:  What we learned from reading 100+ Kubernetes Post-Mortems 
* **Speaker**:  Shimon Tolts + Noaa Barki
* **Type**: Presentation 
* **Level**: Basic
* **Tags**: Kubernetes, DevOps, Post-Mortem

**Description**
A smart person learns from their own mistakes, but a truly wise person learns from the mistakes of others. 

When launching our product, we wanted to learn as much as possible about typical pains in our ecosystem, and did so by reviewing many post-mortems (100+!) to discover the recurring patterns, anti-patterns, and root causes of typical outages in Kubernetes-based systems.  

In this talk we have aggregated for you the insights we gathered, and in particular will review the most obvious DON'Ts and some less obvious ones, that may help you prevent your next production outage by learning from others' real world (horror) stories.

*Please Provide a small paragraph that describes your proposal*
In this talk we have aggregated for you the insights we gathered from reading 100+ Kubernetes post-mortems, and in particular will review the most obvious DON'Ts and some less obvious ones, that may help you prevent your next production outage by learning from others' real world (horror) stories.

**Speaker Bio** (optional)
Shimon Tolts
Shimon established and managed the Software Engineering Infrastructure department for 400 engineers at ironSource. Also as an AWS Community Hero, Shimon runs the largest AWS user-group worldwide and an avid speaker at conferences. Today, Shimon is the CEO & Co-Founder at Datree, an automated policy enforcement solution for Kubernetes. It helps to prevent misconfigurations from code through production. Datree allows to seamlessly manage and enforce policies across Developers and DevOps engineers.

Noaa Barki 
Noaa is a full-stack developer, community manager, and tech writer who wishes to encourage developers to deepen the decisions we make during the development processes, research about the technologies we use and share our knowledge. She started her journey in the 8200 Unit of the IDF Intelligence forces where Noaa took her first steps in software development. In the last 4 years, her work has mainly included Angular, .NET, VanillaJS, and Typescript. She currently develops in React, NodeJS and Golang.

*A short bio of the speaker*

**Comment by mattj-io** [comment]
Thanks @shar1z - will take a look and get back to you soon !

**Comment by shar1z** [comment]
Thank you @mattj-io!! Hope we'll be able to collaborate on the community circuit again! :-)
